In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("fordgobike-tripdataFor201902.csv")

In [3]:
df.shape

(183416, 16)

In [4]:
df.head()

,duration_sec,start_time,end_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bike_id,user_type,member_birth_year,member_gender,bike_share_for_all_trip
0,52185,32:10.1,01:56.0,21.0,Montgomery St BART Station (Market St at 2nd St),37.789625,-122.400811,13.0,Commercial St at Montgomery St,37.794231,-122.402923,4902,Customer,1984.0,Male,No
1,42521,53:21.8,42:03.1,23.0,The Embarcadero at Steuart St,37.791464,-122.391034,81.0,Berry St at 4th St,37.775880,-122.393170,2535,Customer,NaN,NaN,No
2,61854,13:13.2,24:08.1,86.0,Market St at Dolores St,37.769305,-122.426826,3.0,Powell St BART Station (Market St at 4th St),37.786375,-122.404904,5905,Customer,1972.0,Male,No
3,36490,54:26.0,02:36.8,375.0,Grove St at Masonic Ave,37.774836,-122.446546,70.0,Central Ave at Fell St,37.773311,-122.444293,6638,Subscriber,1989.0,Other,No
4,1585,54:18.5,20:44.1,7.0,Frank H Ogawa Plaza,37.804562,-122.271738,222.0,10th Ave at E 15th St,37.792714,-122.248780,4898,Subscriber,1974.0,Male,Yes

In [5]:
df.describe()

,duration_sec,start_station_id,start_station_latitude,start_station_longitude,end_station_id,end_station_latitude,end_station_longitude,bike_id,member_birth_year
count,183416.000000,183219.000000,183416.000000,183416.000000,183219.000000,183416.000000,183416.000000,183416.000000,175151.000000
mean,726.067311,138.590365,37.771221,-122.352661,136.249401,37.771425,-122.352247,4472.890260,1984.806504
std,1794.371831,111.778938,0.099586,0.117100,111.514916,0.099494,0.116677,1664.386068,10.116589
min,61.000000,3.000000,37.317298,-122.453705,3.000000,37.317298,-122.453705,11.000000,1878.000000
25%,325.000000,47.000000,37.770083,-122.412408,44.000000,37.770407,-122.411726,3777.000000,1980.000000
50%,514.000000,104.000000,37.780760,-122.398285,100.000000,37.781010,-122.398279,4958.000000,1987.000000
75%,796.000000,239.000000,37.797280,-122.286533,235.000000,37.797320,-122.288045,5502.000000,1992.000000
max,85444.000000,398.000000,37.880222,-121.874119,398.000000,37.880222,-121.874119,6645.000000,2001.000000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 183416 entries, 0 to 183415
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   duration_sec             183416 non-null  int64
 1   start_time               183416 non-null  str
 2   end_time                 183416 non-null  str
 3   start_station_id         183219 non-null  float64
 4   start_station_name       183219 non-null  str
 5   start_station_latitude   183416 non-null  float64
 6   start_station_longitude  183416 non-null  float64
 7   end_station_id           183219 non-null  float64
 8   end_station_name         183219 non-null  str
 9   end_station_latitude     183416 non-null  float64
 10  end_station_longitude    183416 non-null  float64
 11  bike_id                  183416 non-null  int64
 12  user_type                183416 non-null  str
 13  member_birth_year        175151 non-null  float64
 14  member_gender            175151 non-null  str
 15  bike_share_for_all_trip  183416 non-null  str
dtypes: float64(7), int64(2), str(7)
memory usage: 22.4 MB

In [7]:
dtypes=df.dtypes
n_unique = df.nunique()
pd.DataFrame({"Dtype":dtypes,"Num_unique":n_unique}).T

,duration_sec,start_time,end_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bike_id,user_type,member_birth_year,member_gender,bike_share_for_all_trip
Dtype,int64,str,str,float64,str,float64,float64,float64,str,float64,float64,int64,str,float64,str,str
Num_unique,4752,35783,35767,329,329,334,335,329,329,335,335,4646,2,75,3,2

In [8]:
null = df.isnull().sum()
ratio = null/df.shape[0]
pd.DataFrame({"Null":null,"Ratio":ratio})

                         Null     Ratio
duration_sec                0  0.000000
start_time                  0  0.000000
end_time                    0  0.000000
start_station_id          197  0.001074
start_station_name        197  0.001074
start_station_latitude      0  0.000000
start_station_longitude     0  0.000000
end_station_id            197  0.001074
end_station_name          197  0.001074
end_station_latitude        0  0.000000
end_station_longitude       0  0.000000
bike_id                     0  0.000000
user_type                   0  0.000000
member_birth_year        8265  0.045061
member_gender            8265  0.045061
bike_share_for_all_trip     0  0.000000

In [9]:
df = df.dropna(subset=['start_station_id', 'end_station_id','member_birth_year'])

In [10]:
mode = df['member_gender'].mode()[0]
df['member_gender'] = df['member_gender'].fillna(mode)

In [11]:
null = df.isnull().sum()
ratio = null/df.shape[0]
pd.DataFrame({"Null":null,"Ratio":ratio})

                         Null  Ratio
duration_sec                0    0.0
start_time                  0    0.0
end_time                    0    0.0
start_station_id            0    0.0
start_station_name          0    0.0
start_station_latitude      0    0.0
start_station_longitude     0    0.0
end_station_id              0    0.0
end_station_name            0    0.0
end_station_latitude        0    0.0
end_station_longitude       0    0.0
bike_id                     0    0.0
user_type                   0    0.0
member_birth_year           0    0.0
member_gender               0    0.0
bike_share_for_all_trip     0    0.0

In [12]:
df['user_type'] = df['user_type'].str.strip()

In [13]:
df['member_gender'] = df['member_gender'].str.strip()

In [14]:
df['age'] = 2019 - df['member_birth_year']

In [15]:
df = df[(df['age'] >= 18) & (df['age'] <= 80)]

In [16]:
df['age'].describe()

count    174764.000000
mean         34.125157
std           9.877642
min          18.000000
25%          27.000000
50%          32.000000
75%          39.000000
max          80.000000
Name: age, dtype: float64

In [17]:
df['duration_sec'].describe()

count    174764.000000
mean        704.298454
std        1643.014556
min          61.000000
25%         323.000000
50%         511.000000
75%         789.000000
max       84548.000000
Name: duration_sec, dtype: float64

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
Q1 = df['duration_sec'].quantile(0.25) 
Q3 = df['duration_sec'].quantile(0.75) 
IQR = Q3 - Q1 

Lower_Fence = Q1 - 1.5 * IQR 
Upper_Fence = Q3 + 1.5 * IQR 
Lower_Outliers = df[df['duration_sec'] < Lower_Fence]['duration_sec'].values 
Upper_Outliers = df[df['duration_sec'] > Upper_Fence]['duration_sec'].values 

df = df[(df['duration_sec'] >= Lower_Fence) &(df['duration_sec'] <= Upper_Fence)]

In [20]:
df['duration_sec'].describe()

count    165437.000000
mean        550.385271
std         304.212712
min          61.000000
25%         314.000000
50%         488.000000
75%         731.000000
max        1488.000000
Name: duration_sec, dtype: float64

In [21]:
df['duration_min'] = df['duration_sec'] / 60

In [22]:
df['duration_min'].describe()

count    165437.000000
mean          9.173088
std           5.070212
min           1.016667
25%           5.233333
50%           8.133333
75%          12.183333
max          24.800000
Name: duration_min, dtype: float64

In [23]:
df["start_time"] = pd.to_datetime(df["start_time"], errors="coerce")
df = df.dropna(subset=["start_time"])

C:\Users\arbs\AppData\Local\Temp\ipykernel_7308\4212468393.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["start_time"] = pd.to_datetime(df["start_time"], errors="coerce")

In [24]:
df["hour"] = df["start_time"].dt.hour

In [25]:
hour_data = (
    df.groupby("hour")
    .size()
    .reset_index(name="trips")
    .sort_values("hour")
)

In [26]:
bins = [18, 25, 35, 45, 60, 80]
labels = ['18-25', '26-35', '36-45', '46-60', '61-80']

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=True)

In [27]:
df = pd.get_dummies(
    df,
    columns=[
        'bike_share_for_all_trip'
    ],
    drop_first=True
)

In [28]:
import os

os.makedirs("data/cleaned", exist_ok=True)

In [29]:
df.to_csv("Data/cleaned/cleaned_bike_data.csv", index=False)

In [30]:
df = pd.read_csv("data/cleaned/cleaned_bike_data.csv")

In [31]:
import plotly.express as px
import plotly.graph_objects as go
px.defaults.template = "plotly_white"

# Color palette
COLORS = {
    'primary': '#00BCD4',
    'secondary': '#FF9800', 
    'accent': '#9C27B0',
    'light_blue': '#4FC3F7',
    'dark': '#37474F'
}

In [32]:
hours = hour_data["hour"]
trips_hour = hour_data["trips"]

fig1 = go.Figure()

fig1.add_trace(go.Scatter(
    x=hours,
    y=trips_hour,
    mode="lines+markers",
    line=dict(width=3, color=COLORS["accent"]),
    marker=dict(size=6),
    hovertemplate="Hour: %{x}<br>Trips: %{y}<extra></extra>"
))

fig1.update_layout(
    title=dict(text="Trips by Hour of Day", font=dict(size=18, color=COLORS["dark"])),
    template="plotly_white",
    height=350,

    font=dict(family="Segoe UI, Arial", size=12),
    xaxis=dict(
        title="Hour of Day",
        title_font=dict(size=16),
        dtick=1,
        showgrid=False,
        linecolor="lightgray"
        
    ),
    yaxis=dict(
        title="Number of Trips",
        title_font=dict(size=16),
        showgrid=True,
        gridcolor="rgba(0,0,0,0.05)",
        linecolor="lightgray"
    ),
    margin=dict(l=50, r=30, t=50, b=40)
)

fig1.show()

In [33]:

fig2 = px.histogram(
    df,
    x="duration_min",
    nbins=50,
    title="Trips by Minutes",
    color_discrete_sequence=["#00BCD4"]
)


fig2.update_traces(
    marker_line_width=1,
    marker_line_color="white"
)

fig2.update_layout(
    template="plotly_white",
    height=400,
    xaxis_title="Duration (Minutes)",
    yaxis_title="Number of Trips"
)

fig2.show()

In [34]:
user_counts = df['user_type'].value_counts()

fig3 = go.Figure(data=[go.Pie(
    labels=user_counts.index,
    values=user_counts.values,
    hole=0.65,
    marker=dict(
        colors=[COLORS['primary'], COLORS['secondary']],
        line=dict(width=2, color='white')
    ),
    textinfo='none',
    hoverinfo='label+percent'
)])

user_counts = df['user_type'].value_counts()
total = user_counts.sum()

max_label = user_counts.idxmax()
max_percent = (user_counts.max() / total) * 100
fig3.update_layout(
    title=dict(text='Subscriber vs Customer Usage', font=dict(size=24, color=COLORS['dark'])),
    template='plotly_white',
    height=350,
    width=500,
    font=dict(family="Segoe UI, Arial", size=12),
    paper_bgcolor='white',
    showlegend=True,
    legend=dict(orientation="h", yanchor="bottom", y=-0.15, x=0.5, xanchor="center"),
    margin=dict(l=40, r=40, t=50, b=60),
    annotations=[
        dict(
            text=f"{max_percent:.1f}%",
            x=0.5,
            y=0.5,
            font_size=28,
            showarrow=False,
            font_family="Segoe UI"
        ),
        dict(
            text=max_label,
            x=0.5,
            y=0.35,
            font_size=14,
            showarrow=False,
            font_color='gray'
        )
    ]
)

In [35]:
gender_counts = df['member_gender'].value_counts()

gender_percent = (gender_counts / gender_counts.sum()) * 100

order = ['Male', 'Female', 'Other']
gender_counts = gender_counts.reindex(order).fillna(0)
gender_percent = gender_percent.reindex(order).fillna(0)

fig4 = go.Figure()

fig4.add_trace(go.Bar(
    x=gender_counts.index,
    y=gender_counts.values,
    marker=dict(
        color=[COLORS['primary'], COLORS['secondary'], COLORS['accent']],
        line=dict(width=1, color='white')
    ),
    text=[f"{p:.1f}%" for p in gender_percent.values],
    textposition='none',
    textfont=dict(size=12, color=COLORS['dark'])
))

fig4.update_layout(
    title=dict(text='Trips By Gender', font=dict(size=18, color=COLORS['dark'])),
    template='plotly_white',
    height=400,
    width =500,
    font=dict(family="Segoe UI, Arial", size=12),
    paper_bgcolor='white',
    plot_bgcolor='white',
    xaxis=dict(showgrid=False, linecolor='lightgray'),
    yaxis=dict(showgrid=True, gridcolor='rgba(0,0,0,0.05)', linecolor='lightgray'),
    margin=dict(l=40, r=30, t=50, b=40),
    bargap=0.3
)

fig4.show()

In [36]:
age_data = df['age_group'].value_counts().sort_index().reset_index()
age_data.columns = ['age_group', 'trips']

fig5 = px.bar(
    age_data,
    x='age_group',
    y='trips',
    title='Trips by Age Group',
    color='age_group',
    color_discrete_sequence=[
        COLORS['secondary'],
        COLORS['primary'],
        COLORS['accent'],
        "#80DEEA", 
        "#43BC75"
    ]
)

fig5.update_layout(
    template='plotly_white',
    xaxis_title='Age Group',
    yaxis_title='Number of Trips'
)

fig5.show()

In [49]:
top_stations = (
    df['start_station_name']
    .value_counts()
    .head(10)
    .sort_values(ascending=False)  
    )
stations = top_stations.index
counts = top_stations.values

colors_stations = [
    COLORS['primary'] if value in top_stations.head(3).values
    else COLORS['light_blue']
    for value in counts
]

fig6 = go.Figure()

fig6.add_trace(go.Bar(
    y=stations,
    x=counts,
    orientation='h',
    marker=dict(color=colors_stations, line=dict(width=1, color='white')),
    text=[f'{c:,}' for c in counts],
    textposition='inside',
    textfont=dict(size=10, color=COLORS['dark'])
))
fig6.update_layout(
    title=dict(text='Top 10 Stations', font=dict(size=24, color=COLORS['dark'])),
    template='plotly_white',
    height=400,
    font=dict(family="Segoe UI, Arial", size=11),
    paper_bgcolor='white',
    plot_bgcolor='white',
    xaxis=dict(showgrid=True, gridcolor='rgba(0,0,0,0.05)', linecolor='lightgray', title='Number of Trips'),
    yaxis=dict(showgrid=False, linecolor='lightgray', autorange="reversed"),
    margin=dict(l=120, r=60, t=50, b=40),
    bargap=0.2
)